replicaCount: 3

image:
  repository: tejasbhosale008/helloworld
  tag: 165857b
  pullPolicy: IfNotPresent
env:
  - name: LOG_LEVEL
    value: INFO
  - name: APP_ENV
    value: prod

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 80 # Optional
ingress:
  enabled: false
  className: ""  # Optional: e.g., "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: hello-minikube.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hello-minikube-tls
      hosts:
        - hello-minikube.local
