replicaCount: 1

image:
  repository: tejasbhosale008/helloworld
  tag: 165857b
  pullPolicy: IfNotPresent
env:
  - name: LOG_LEVEL
    value: ERROR
  - name: APP_ENV
    value: dev

resources:
  requests:
    cpu: 250m
    memory: 250Mi
  limits:
    cpu: 500m
    memory: 512Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 80 # Optional

ingress:
  enabled: true
  className: ""  # Optional: e.g., "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: hello-minikube.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hello-minikube-tls
      hosts:
        - hello-minikube.local
