replicaCount: 5

image:
  repository: tejasbhosale008/helloworld
  tag: 165857b
  pullPolicy: IfNotPresent
env:
  - name: LOG_LEVEL
    value: INFO

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

