apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-world-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - hello-minikube.local
      secretName: hello-minikube-tls
  rules:
    - host: hello-minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80

