
services:
  jenkins:
    build: .
    container_name: jenkins
    user: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: tcp://docker:2375
      KUBECONFIG: /var/jenkins_home/.kube/config
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - docker
    restart: unless-stopped

  docker:
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=  # disables TLS for simplicity (only for trusted network!)
    volumes:
      - dind-data:/var/lib/docker
    restart: unless-stopped

volumes:
  jenkins_home:
  dind-data:

